---
title: "Combine_data"
author: "ERM"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 200px;
}
```

```{r  package loading}
library(tidyverse)
library(kableExtra)
library(broom)
library(RColorBrewer)
library("TxDb.Hsapiens.UCSC.hg38.knownGene")
library("org.Hs.eg.db")
library(rtracklayer)
library(ggfortify)
library(readr)
library(BiocGenerics)
library(gridExtra)
library(VennDiagram)
library(scales)
library(ggVennDiagram)
library(BiocParallel)
library(ggpubr)
library(edgeR)
library(genomation)
library(ggsignif)
library(plyranges)
library(ggrepel)
library(ComplexHeatmap)
library(cowplot)
library(smplot2)

```


```{r}
# toplistall_RNA <- readRDS("data/other_papers/toplistall_RNA.RDS") 
# toplistall_RNA <- toplistall_RNA %>% 
#   mutate(logFC = logFC*(-1))
# toplist_ATAC <- readRDS("data/Final_four_data/toplist_ff.RDS")

Collapsed_H3k27ac_NG <- read_delim("data/Final_four_data/H3K27ac_files/Collapsed_H3k27ac_NG.txt",delim = "\t",col_names = TRUE)
Collapsed_new_peaks <- read_delim("data/Final_four_data/collapsed_new_peaks.txt", delim = "\t", col_names = TRUE)


RNA_median_3_lfc <- readRDS("data/other_papers/RNA_median_3_lfc.RDS")
RNA_median_24_lfc <- readRDS("data/other_papers/RNA_median_24_lfc.RDS")
overlap_df_ggplot <- readRDS("data/Final_four_data/LFC_ATAC_K27ac.RDS")
AC_median_3_lfc <- read_csv("data/Final_four_data/AC_median_3_lfc.csv")
AC_median_24_lfc <- read_csv("data/Final_four_data/AC_median_24_lfc.csv")
ATAC_24_lfc <- read_csv("data/Final_four_data/median_24_lfc.csv") 
ATAC_3_lfc <- read_csv("data/Final_four_data/median_3_lfc.csv")

joined_LFC_df <- overlap_df_ggplot %>%
  left_join(.,(Collapsed_new_peaks %>%
                 dplyr::select(Peakid,dist_to_NG, NCBI_gene:SYMBOL)),
            by=c("peakid"="Peakid")) %>% 
  left_join(., RNA_median_3_lfc ,
                # %>%
                #   dplyr::select(SYMBOL,RNA_3h_lfc)), 
            by=c("SYMBOL"="SYMBOL", "NCBI_gene"="ENTREZID")) %>%
  left_join(., RNA_median_24_lfc,# %>%
                  # dplyr::select(SYMBOL,RNA_24h_lfc)),
             by=c("SYMBOL"="SYMBOL", "NCBI_gene"="ENTREZID")) 

lt1<- readRDS("data/Final_four_data/updated_RNA_gene_lookuptable")

checklist <- lt1 %>% 
  separate_longer_delim(.,col= ENTREZID, delim= ":") %>% 
separate_longer_delim(.,col= SYMBOL, delim= ":") %>% 
  dplyr::select(ENTREZID,SYMBOL) %>% 
  mutate(ENTREZID=as.numeric(ENTREZID)) %>% 
  distinct()

# schneider_closest_output <- readRDS("data/other_papers/Schneider_closestgene_SNP_file.RDS") %>% 
#   left_join(., checklist, by=c("ENTREZID"="ENTREZID"))

# schneider_gr <- schneider_closest_output %>% 
#   dplyr::select(chrom,start,stop,RSID,ENTREZID) %>% 
#   left_join(., (checklist %>% mutate(ENTREZID=as.numeric(ENTREZID))) , by=c("ENTREZID"="ENTREZID")) %>% 
#   GRanges()
# 
# schneider_10k_gr <- schneider_closest_output %>% 
#   mutate(start=(start-5000),stop=(stop+4999), width=10000) %>% 
#   dplyr::select(chrom,start,stop,RSID,ENTREZID) %>% 
#   left_join(., checklist , by=c("ENTREZID"="ENTREZID")) %>% 
#   GRanges()
# SNP_peak_check <- join_overlap_intersect(TSS_assigned_NG_gr,schneider_gr) %>% 
#   as.data.frame()
# 
# SNP_peak_check_10k <- join_overlap_intersect(TSS_assigned_NG_gr,schneider_10k_gr) %>% 
#   as.data.frame()

new_SNP_peak_check_10k <- readRDS("data/Final_four_data/new_SNP_peak_check_10k.RDS")
  
new_SNP_peak_check <-   readRDS("data/Final_four_data/new_SNP_peak_check.RDS")
point_only <- new_SNP_peak_check
# new_SNP_pc_gr <- new_SNP_peak_check_10k
new_SNP_peak_check_10k %>% dplyr::filter(ENTREZID.x !=ENTREZID.y)
# schneider_gr %>% write_bed(.,"data/Final_four_data/meme_bed/Schnieder_SNPs.bed")


ATAC_peaks_gr <- Collapsed_new_peaks %>% GRanges()

# point_only <- join_overlap_intersect(schneider_gr,ATAC_peaks_gr)
# expand_schneider <- join_overlap_intersect(ATAC_peaks_gr,schneider_10k_gr)
library(readxl)
Reheat_data <- read_excel("data/other_papers/jah36123-sup-0002-tables2.xlsx")
top_reheat <- Reheat_data %>% 
  dplyr::filter(fisher_pvalue<0.005)
schneider_short_list <- point_only %>% as.data.frame
# 
# peakAnnoList_ff_motif <- readRDS("data/Final_four_data/peakAnnoList_ff_motif.RDS")
# 
# background_peaks <- as.data.frame(peakAnnoList_ff_motif$background) 
# EAR_df <- as.data.frame(peakAnnoList_ff_motif$EAR)
# ESR_df <- as.data.frame(peakAnnoList_ff_motif$ESR)
# LR_df <- as.data.frame(peakAnnoList_ff_motif$LR)
# NR_df <- as.data.frame(peakAnnoList_ff_motif$NR)
# open_3med <- ATAC_3_lfc %>% 
#   dplyr::filter(med_3h_lfc > 0)
# 
# close_3med <- ATAC_3_lfc %>% 
#   dplyr::filter(med_3h_lfc < 0)
# 
# open_24med <- ATAC_24_lfc %>% 
#   dplyr::filter(med_24h_lfc > 0)
# 
# close_24med <- ATAC_24_lfc %>% 
#   dplyr::filter(med_24h_lfc < 0)
# 
# medA <- ATAC_3_lfc %>% 
#   left_join(ATAC_24_lfc, by=c("peak"="peak")) %>% 
#   dplyr::filter(med_3h_lfc > 0 & med_24h_lfc>0)
# 
# medB <- ATAC_3_lfc %>% 
#   left_join(ATAC_24_lfc, by=c("peak"="peak")) %>% 
#   dplyr::filter(med_3h_lfc < 0 & med_24h_lfc < 0)
#  
# medC <- ATAC_3_lfc %>% 
#   left_join(ATAC_24_lfc, by=c("peak"="peak")) %>% 
#   dplyr::filter(med_3h_lfc > 0& med_24h_lfc <0)
#   
# 
# medD <- ATAC_3_lfc %>% 
#  left_join(ATAC_24_lfc, by=c("peak"="peak"))%>% 
#   dplyr::filter(med_3h_lfc < 0 & med_24h_lfc > 0)
 

Nine_te_df <- readRDS("data/Final_four_data/Nine_group_TE_df.RDS")

match <- Nine_te_df %>% distinct(Peakid,TEstatus,mrc,.keep_all = TRUE) 
# NR <- NR_df %>% dplyr::select(Peakid)
# EAR_open <- EAR_df %>% dplyr::select(Peakid) %>% dplyr::filter(Peakid %in% open_3med$peak)
# EAR_close <-EAR_df %>% dplyr::select(Peakid) %>% dplyr::filter(Peakid %in% close_3med$peak)
# ESR_open <- ESR_df %>% dplyr::select(Peakid) %>% dplyr::filter(Peakid %in% medA$peak)
# ESR_close <- ESR_df %>% dplyr::select(Peakid) %>% dplyr::filter(Peakid %in% medB$peak)
# LR_open <- LR_df %>% dplyr::select(Peakid) %>% dplyr::filter(Peakid %in% open_24med$peak)
# LR_close <- LR_df %>% dplyr::select(Peakid) %>% dplyr::filter(Peakid %in% open_24med$peak)
# ESR_opcl <- ESR_df %>% dplyr::select(Peakid) %>% dplyr::filter(Peakid %in% medC$peak)
# ESR_clop <- ESR_df %>% dplyr::select(Peakid) %>% dplyr::filter(Peakid %in% medD$peak)
# expand_schneider %>% as.data.frame() %>% 
#   dplyr::select(Peakid,RSID,NCBI_gene:SYMBOL.y) %>% dplyr::filter(grepl("rs425*", RSID))


Knowles_dox_eQTL <- readRDS("data/Knowles_5.RDS")
Knowles_mar_eQTL <- readRDS("data/Knowles_4.RDS")

dox_eQTL_gr <- Knowles_dox_eQTL %>% 
  distinct(RSID,.keep_all = TRUE) %>%
  mutate(CHR_ID=(gsub("chr","",chr))) %>% 
  dplyr::rename("SNPS"=RSID,"CHR_POS"=pos) %>% 
  dplyr::select(CHR_ID, CHR_POS,SNPS) %>% 
  mutate(CHR_ID=as.numeric(CHR_ID), CHR_POS=as.numeric(CHR_POS)) %>%
  na.omit() %>%
  mutate(gwas="eQTL") %>% 
  mutate(start=CHR_POS, end=CHR_POS, chr=paste0("chr",CHR_ID)) %>% 
  GRanges()
          
 
mar_eQTL_gr <- Knowles_mar_eQTL %>% 
  distinct(RSID,.keep_all = TRUE) %>%
  mutate(CHR_ID=(gsub("chr","",chr))) %>% 
  dplyr::rename("SNPS"=RSID,"CHR_POS"=pos) %>% 
  dplyr::select(CHR_ID, CHR_POS,SNPS) %>% 
  mutate(gwas="beQTL") %>% 
  mutate(CHR_ID=as.numeric(CHR_ID), CHR_POS=as.numeric(CHR_POS)) %>%
  na.omit() %>%
  mutate(start=CHR_POS, end=CHR_POS, chr=paste0("chr",CHR_ID)) %>% 
  GRanges()
base_eqtl_SNPS <-
  join_overlap_intersect(ATAC_peaks_gr,mar_eQTL_gr) %>% 
  as.data.frame() 

eqtl_SNPs <-
  join_overlap_intersect(ATAC_peaks_gr,eQTL_gr) %>%
  as.data.frame() 

test <- eqtl_SNPs %>% 
  dplyr::filter(Peakid %in% new_SNP_peak_check_10k$Peakid)

join_overlap_intersect((new_SNP_peak_check_10k %>% GRanges() ),beQTL_gr) %>%
  as.data.frame() 
```

```{r mast}
####adding in MAST matches
# "~/ATAC_meme_data/200bp/EAR_close_hits.txt"
mast_test_results <- xmlParse("~/ATAC_meme_data/200bp/mast_output/EAR_close/mast.xml")

# Function to extract hit details within each sequence
motifs <- xpathApply(mast_test_results, "//sequence", function(sequence_node) {
  # Get sequence metadata
  seqname <- xmlGetAttr(sequence_node, "name")
  seq_db <- xmlGetAttr(sequence_node, "db")
  seq_length <- as.numeric(xmlGetAttr(sequence_node, "length"))

  # Extract each `hit` node from nested `seg` nodes
  hits <- xpathApply(sequence_node, ".//hit", function(hit_node) {
    list(
      seqname = seqname,
      db = seq_db,
      length = seq_length,
      pos = as.numeric(xmlGetAttr(hit_node, "pos")),
      idx = as.numeric(xmlGetAttr(hit_node, "idx")),
      rc = xmlGetAttr(hit_node, "rc"),  # reverse-complement flag
      pvalue = as.numeric(xmlGetAttr(hit_node, "pvalue"))
    )
  })

  # Convert each hit to a data frame
  do.call(rbind, lapply(hits, as.data.frame))
})
motifs_df <- do.call(rbind, motifs)
# mast_gr <- GRanges(seqnames = Rle(motifs_df$seqname),
#                    ranges = IRanges(start = motifs_df$start, width = 1),
#                    # adjust width if needed
#                    strand = Rle(motifs_df$strand),
#                    motif_id = motifs_df$motif_id)

print(head(motifs_df))

mast_gr <- GRanges(
  seqnames = Rle(motifs_df$seqname),
  ranges = IRanges(start = motifs_df$pos, width = 1),  # adjust width if needed
  strand = Rle(ifelse(motifs_df$rc == "y", "-", "+")),
  pvalue = motifs_df$pvalue,
  idx = motifs_df$idx
)
mast_gr

join_overlap_intersect(new_SNP_peak_check)
```


```{r, fig.height=9, fig.width=6}
schneider_df <-
new_SNP_peak_check_10k%>% as.data.frame() %>% 
  dplyr::select(Peakid,RSID,ENTREZID.x:dist_to_NG,ENTREZID.y:SYMBOL.y, dist_SNP_NG_TSS) %>% 
  mutate(SYMBOL=if_else(is.na(SYMBOL.y),SYMBOL.x,SYMBOL.y)) %>% 
mutate(ENTREZID=if_else(is.na(ENTREZID.y),ENTREZID.x,ENTREZID.y))%>% 
 dplyr::select(Peakid, RSID, ENTREZID, SYMBOL) %>% 
  distinct(Peakid,RSID,.keep_all = TRUE) %>% 
  # left_join(., joined_LFC_df,by = c("Peakid"="peakid", "ENTREZID"="NCBI_gene","SYMBOL"="SYMBOL")) #%>% 
  # dplyr::select(Peakid:Geneid, AC_3h_lfc, AC_24h_lfc) %>% 
  left_join(., (ATAC_3_lfc %>% dplyr::select(peak,med_3h_lfc)),by=c("Peakid"="peak")) %>% 
  left_join(., (ATAC_24_lfc %>% dplyr::select(peak,med_24h_lfc)),by=c("Peakid"="peak"))%>% 
### peaks left out here were chopped due to low counts (row_means<0) %>% 
  mutate(ENTREZID= if_else(RSID=="rs36022097","8970",ENTREZID),
         SYMBOL=if_else(RSID=="rs36022097","H2BC11",SYMBOL)) %>% 
dplyr::filter(!is.na(med_24h_lfc)) %>% 
  left_join(., RNA_median_3_lfc,by =c("ENTREZID"="ENTREZID")) %>% 
  left_join(., RNA_median_24_lfc,by =c("ENTREZID"="ENTREZID", "SYMBOL.y"="SYMBOL")) %>% 
  mutate(reheat=if_else(SYMBOL.x %in% Reheat_data$gene,"reheat_gene","not_reheat_gene")) %>% 
  dplyr::filter(!is.na(med_3h_lfc)) %>% 
  distinct(RSID,.keep_all = TRUE) %>% 
  dplyr::select(RSID,Peakid,med_3h_lfc,med_24h_lfc,,RNA_3h_lfc,RNA_24h_lfc, ENTREZID,SYMBOL.x,reheat) %>% #AC_3h_lfc,AC_24h_lfc) %>% 
  tidyr::unite(name,RSID,SYMBOL.x,Peakid,sep ="_",remove=FALSE) %>% 
  left_join(.,(match %>% 
                 group_by(Peakid) %>%
                 filter(!(TEstatus=="not_TE_peak" & any (TEstatus == "TE_peak"))) %>% 
                 ungroup() %>%
                 distinct(TEstatus,Peakid,.keep_all = TRUE)),
            by = c("Peakid"="Peakid")) %>% 
  group_by(Peakid) %>% 
 summarize(name=unique(name),
           RSID=unique(RSID),
           med_3h_lfc=unique(med_3h_lfc),
           med_24h_lfc=unique(med_24h_lfc),
           # AC_3h_lfc=unique(AC_3h_lfc),
           # AC_24h_lfc=unique(AC_24h_lfc),
           RNA_3h_lfc=unique(RNA_3h_lfc),
           RNA_24h_lfc=unique(RNA_24h_lfc),
          repClass=paste(unique(repClass),collapse=":"),
           TEstatus=paste(unique(TEstatus),collapse=";"),
          SYMBOL.x=paste(unique(SYMBOL.x),collapse=";"),
           reheat=paste(unique(reheat),collapse=";"),
          mrc=unique(mrc)) %>% 
  mutate(point_ol=if_else(RSID %in% point_only$RSID,"yes","no")) %>% 
  mutate(eQTL=if_else(RSID %in% eqtl_SNPs$SNPS,"yes",if_else(Peakid %in% eqtl_SNPs$Peakid,"yes","no")))

schneider_mat <- schneider_df %>% 
  ungroup() %>% 
  dplyr::select(name,med_3h_lfc:RNA_24h_lfc) %>% 
  column_to_rownames("name") %>% 
  as.matrix()
schneider_name_mat <- schneider_df %>% 
  ungroup() %>% 
  dplyr::select(name,TEstatus,mrc,reheat,point_ol)

row_anno <- ComplexHeatmap::rowAnnotation(TE_status=schneider_name_mat$TEstatus,reheat_status=schneider_name_mat$reheat,MRC=schneider_name_mat$mrc,direct_overlap=schneider_name_mat$point_ol,col= list(TE_status= c("TE_peak"="goldenrod","TE_peak;not_TE_peak"="goldenrod","not_TE_peak;TE_peak"="goldenrod","not_TE_peak"="lightblue"), 
                                                                                                MRC = c("EAR_open" = "#F8766D",   "EAR_close" = "#f6483c",
    "ESR_open" = "#7CAE00",
    "ESR_close" = "#587b00",
     "ESR_opcl"="grey40",
    "ESR_C"="grey40",
      "ESR_clop"="tan",
    "ESR_D"="tan",
     "ESR_OC" = "#6a9500",
     "LR_open" = "#00BFC4",
     "LR_close" = "#008d91",
     "NR" = "#C77CFF",
    "not_mrc"="black"
  ),
  reheat_status=c("reheat_gene"="green","not_reheat_gene"="orange")
),direct_overlap=c("yes"="red","no"="grey8"))
  
ComplexHeatmap::Heatmap(schneider_mat,
                        left_annotation = row_anno,
                        show_row_names = TRUE,
                        show_column_names = TRUE,cluster_rows = FALSE,cluster_columns = FALSE)



```
#### GWAS SNP overlap log2cpm


### TTN
```{r toplistdata}
drug_pal <- c("#8B006D","#DF707E","#F1B72B", "#3386DD","#707031","#41B333")
# K27_counts <-  readRDS("data/Final_four_data/All_Raodahpeaks.RDS")
ATAC_counts <- readRDS("data/Final_four_data/x4_filtered.RDS")
RNA_counts <- readRDS("data/other_papers/Counts_RNA_ERMatthews.RDS")
# overlap_atac_ac_peaks <- readRDS( "data/Final_four_data/overlapping_ac_atac_peaks.RDS")
TNT_peak <- data.frame(peak="chr2.178547784.178549172", RNA="TTN", ENTREZID=7273)
 AS1 <- 100506866
RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% TNT_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle("Titin (TTN) RNA expression")+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")
 
RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% AS1) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle("Titin-AS1 (TTN-AS1) RNA expression")+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")
 


ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) %>% 
  dplyr::filter(row.names(.) %in% TNT_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle("Titin (TTN) ATAC accessibility")+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")
```
### IGSFB9
```{r IGSFB9}

IGSF9B_peak <- data.frame(peak="chr11.133816825.133817041", RNA="IGSFB9", ENTREZID=22997)

RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% IGSF9B_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle("IGSF9B RNA expression")+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")


ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) %>% 
  dplyr::filter(row.names(.) %in% IGSF9B_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle("IGSF9B ATAC accessibility")+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

schneider_df
```
### rs12051934 ALPK2

```{r ALPK2}

ALPK2_peak <- data.frame(peak="chr18.58336709.58336869", RNA="ALPK2", ENTREZID=115701)

RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% ALPK2_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle("ALPK2 RNA expression")+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")


ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) %>% 
  dplyr::filter(row.names(.) %in% ALPK2_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle("ALPK2 ATAC accessibility")+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

```
### rs4916358 PRDX6 
```{r PRDX6}
schneider_df %>% dplyr::filter(SYMBOL.x=="PRDX6")
PRDX6_peak <- data.frame(peak="chr1.173473597.173473889", RNA="PRDX6", ENTREZID=9588)

RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% PRDX6_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(PRDX6_peak$RNA," RNA expression"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")



plotpanelATAC <- ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) 

plotpanelATAC %>% 
  dplyr::filter(row.names(.) %in% PRDX6_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
   ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(PRDX6_peak$RNA," gene and \n",PRDX6_peak$peak," ATAC accessibility"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

```


### MSANTD2-AS1 rs7111513
```{r MSANTD2-AS1-1}
schneider_df %>% dplyr::filter(RSID=="rs7111513")
MSANTD2_AS1_peak <- data.frame(peak="chr11.124863016.124863456",RNA="MSANTD2-AS1", ENTREZID=100507283)

RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% MSANTD2_AS1_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(MSANTD2_AS1_peak$RNA," RNA expression"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")



plotpanelATAC <- ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) 

plotpanelATAC %>% 
  dplyr::filter(row.names(.) %in% MSANTD2_AS1_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
   ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(MSANTD2_AS1_peak$RNA," gene and \n",MSANTD2_AS1_peak$peak," ATAC accessibility"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

```


### MSANTD2-AS1 rs7111513
```{r MSANTD2-AS1-1_2}
schneider_df %>% dplyr::filter(RSID=="rs5017048")
MSANTD2_AS1_peak <- data.frame(peak="chr11.124863016.124863456", RNA="MSANTD2-AS1", ENTREZID=	
100507283)

RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% MSANTD2_AS1_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(MSANTD2_AS1_peak$RNA," RNA expression"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")



plotpanelATAC <- ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) 

plotpanelATAC %>% 
  dplyr::filter(row.names(.) %in% MSANTD2_AS1_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
   ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(MSANTD2_AS1_peak$RNA," gene and \n",MSANTD2_AS1_peak$peak," ATAC accessibility"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

```



### SLC8A1 rs6746423
```{r SLC8A1}

schneider_df %>% dplyr::filter(RSID=="rs6746423")
SLC8A1_peak <- data.frame(peak="chr2.41038390.41038934", RNA="SLC8A1", ENTREZID=6546)


RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% SLC8A1_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(SLC8A1_peak$RNA," RNA expression"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")



plotpanelATAC <- ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) 

plotpanelATAC %>% 
  dplyr::filter(row.names(.) %in% SLC8A1_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
   ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(SLC8A1_peak$RNA," gene and \n",SLC8A1_peak$peak," ATAC accessibility"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

```



### CDPF1 rs4253763; rs11090819
```{r CDPF1}

schneider_df %>% dplyr::filter(RSID=="rs4253763")
CDPF1_peak <- data.frame(peak="chr22.46225398.46226192", RNA="CDPF1", ENTREZID=	
150383)


RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% CDPF1_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(CDPF1_peak$RNA," RNA expression"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")



plotpanelATAC <- ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) 

plotpanelATAC %>% 
  dplyr::filter(row.names(.) %in% CDPF1_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
   ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(CDPF1_peak$RNA," gene and \n",CDPF1_peak$peak," ATAC accessibility"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

```


### GIN1 rs6860588; rs3776874; rs11952361
```{r GIN1}
schneider_df %>% dplyr::filter(RSID=="rs11952361")
GIN1_peak <- data.frame(peak="chr5.102947036.102947471", RNA="GIN1", ENTREZID=	54826)

RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% GIN1_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(GIN1_peak$RNA," RNA expression"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")



plotpanelATAC <- ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) 

plotpanelATAC %>% 
  dplyr::filter(row.names(.) %in% GIN1_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
   ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(GIN1_peak$RNA," gene and \n",GIN1_peak$peak," ATAC accessibility"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

```


### OGFRL1 rs1204328
```{r OGFRL1}
schneider_df %>% dplyr::filter(RSID=="rs1204328")
OGFRL1_peak <- data.frame(peak="chr6.71712533.71713167", RNA="OGFRL1", ENTREZID=		79627)

RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% OGFRL1_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(OGFRL1_peak$RNA," RNA expression"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")



plotpanelATAC <- ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) 

plotpanelATAC %>% 
  dplyr::filter(row.names(.) %in% OGFRL1_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
   ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(OGFRL1_peak$RNA," gene and \n",OGFRL1_peak$peak," ATAC accessibility"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

```



### ATP6V1B2 rs12548222
```{r ATP6V1B2}
schneider_df %>% dplyr::filter(RSID=="rs12548222")
ATP6V1B2_peak <- data.frame(peak="chr8.20115130.20115538", RNA="ATP6V1B2", ENTREZID=	526)

RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% ATP6V1B2_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(ATP6V1B2_peak$RNA," RNA expression"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")



plotpanelATAC <- ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) 

plotpanelATAC %>% 
  dplyr::filter(row.names(.) %in% ATP6V1B2_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
   ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(ATP6V1B2_peak$RNA," gene and \n",ATP6V1B2_peak$peak," ATAC accessibility"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

```



### ARFGEF1 rs7820882;rs11779485
```{r ARFGEF1}
schneider_df %>% dplyr::filter(RSID=="rs7820882")
ARFGEF1_peak <- data.frame(peak="chr8.67481465.67482210", RNA="ARFGEF1", ENTREZID=	10565)

RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% ARFGEF1_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(ARFGEF1_peak$RNA," RNA expression"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")



plotpanelATAC <- ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) 

plotpanelATAC %>% 
  dplyr::filter(row.names(.) %in% ARFGEF1_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
   ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(ARFGEF1_peak$RNA," gene and \n",ARFGEF1_peak$peak," ATAC accessibility"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

```



### ARFGEF1 rs4737838
```{r ARFGEF1_2}
schneider_df %>% dplyr::filter(RSID=="rs4737838")
ARFGEF1_peak <- data.frame(peak="chr8.67503991.67504420", RNA="ARFGEF1", ENTREZID=	10565)

RNA_counts %>% 
  column_to_rownames("ENTREZID") %>% 
  cpm(., log = TRUE) %>% 
  as.data.frame() %>% 
  dplyr::filter(row.names(.) %in% ARFGEF1_peak$ENTREZID) %>% 
  mutate(ENTREZID = row.names(.)) %>% 
  pivot_longer(cols = !ENTREZID, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("trt","ind","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
  ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(ARFGEF1_peak$RNA," RNA expression"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm RNA")



plotpanelATAC <- ATAC_counts %>% 
  cpm(., log = TRUE) %>% 
   as.data.frame() %>%
  rename_with(.,~gsub(pattern = "Ind1_75", replacement = "1_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind2_87", replacement = "2_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind3_77", replacement = "3_",.)) %>%
  rename_with(.,~gsub(pattern = "Ind6_71", replacement = "6_",.)) %>%
  rename_with(.,~gsub( "DX" ,'DOX',.)) %>%
  rename_with(.,~gsub( "DA" ,'DNR',.)) %>%
  rename_with(.,~gsub( "E" ,'EPI',.)) %>%
  rename_with(.,~gsub( "T" ,'TRZ',.)) %>%
  rename_with(.,~gsub( "M" ,'MTX',.)) %>%
  rename_with(.,~gsub( "V" ,'VEH',.)) %>%
  rename_with(.,~gsub("24h","_24h",.)) %>%
  rename_with(.,~gsub("3h","_3h",.)) 

plotpanelATAC %>% 
  dplyr::filter(row.names(.) %in% ARFGEF1_peak$peak) %>% 
  mutate(Peakid = row.names(.)) %>% 
  pivot_longer(cols = !Peakid, names_to = "sample", values_to = "counts") %>% 
  separate("sample", into = c("ind","trt","time")) %>% 
  mutate(time=factor(time, levels = c("3h","24h"))) %>% 
  mutate(trt=factor(trt, levels= c("DOX","EPI","DNR","MTX","TRZ","VEH"))) %>% 
   ggplot(., aes (x = time, y=counts))+
  geom_boxplot(aes(fill=trt))+
  ggtitle(paste(ARFGEF1_peak$RNA," gene and \n",ARFGEF1_peak$peak," ATAC accessibility"))+
  scale_fill_manual(values = drug_pal)+
  theme_bw()+
  ylab("log2 cpm ATAC")

```




