---
title: "Jaspar_motif_norm"
author: "Renee Matthews"
date: "2025-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 200px;
}
```


```{r package loading}
library(tidyverse)
library(cowplot)
library(kableExtra)
library(broom)
library(RColorBrewer)
library(ChIPseeker)
library("TxDb.Hsapiens.UCSC.hg38.knownGene")
library("org.Hs.eg.db")
library(rtracklayer)
library(edgeR)
library(ggfortify)
library(limma)
library(readr)
library(BiocGenerics)
library(gridExtra)
library(VennDiagram)
library(scales)
library(Cormotif)
library(BiocParallel)
library(ggpubr)
library(devtools)
library(JASPAR2022)
library(TFBSTools)
library(MotifDb)
library(BSgenome.Hsapiens.UCSC.hg38)
library(data.table)
library(universalmotif)
library(ggseqlogo)
library(motifmatchr)
library(gridExtra)

```

```{r mrc palatte}
mrc_palette <- c(
    "EAR_open" = "#F8766D",
    "EAR_close" = "#f6483c",
    "ESR_open" = "#7CAE00",
    "ESR_close" = "#587b00",
    "ESR_C"="grey40",
     "ESR_opcl"="grey40",
    "ESR_D"="tan",
     "ESR_clop"="tan",
     "LR_open" = "#00BFC4",
     "LR_close" = "#008d91",
     "NR" = "#C77CFF"
  )


```

### EAR_open data EAR_open
```{r EAR_open xstreme output data loading}


EAR_open_sea_disc <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/EAR_open_xstreme/sea_disc_out/sea.tsv") %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)
EAR_open_sea_known <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/EAR_open_xstreme/sea_out/sea.tsv") %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)
EAR_open_xstreme <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/EAR_open_xstreme/xstreme.tsv") %>% slice_head(n = length(.$ID)-3)
EAR_open_sea_all <- rbind(EAR_open_sea_disc, EAR_open_sea_known) %>% 
  arrange(ID, desc(source == "known")) %>%  
  distinct(ID, .keep_all = TRUE)

```

```{r looking at EAR_open data}
EAR_open_combo <- EAR_open_xstreme %>% 
  dplyr::select(SEED_MOTIF:EVALUE_ACC,SIM_MOTIF) %>% 
  left_join(., EAR_open_sea_all, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ NA_character_
)) %>% 
  dplyr::select(RANK,CLUSTER,SIM_MOTIF,ALT_ID, ID,CONSENSUS.x,motif_name,EVALUE.y,QVALUE,TP:ENR_RATIO) %>% 
  arrange(.,EVALUE.y) %>% 
  mutate(mrc_type="EAR_open")

EAR_open_combo %>% 
  dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
  kable(., caption = "Enriched motifs 200 bp in EAR open v NR") %>%
  kable_paper("striped", full_width = TRUE) %>%
  kable_styling(full_width = FALSE, font_size = 16) %>%
  scroll_box(height = "500px")

```
```{r EAR_open}
ER_rat <- 1.25
mrc_type <- "EAR_open"
EAR_open_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*1.25), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1.25,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

EAR_open_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>%
  distinct(CLUSTER,.keep_all = TRUE) %>% 
  slice_head(n=5) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*.5), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./.5,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

```


### EAR_close data
```{r EAR_close xstreme output data loading}


EAR_close_sea_disc <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/EAR_close_xstreme/sea_disc_out/sea.tsv") %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)
EAR_close_sea_known <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/EAR_close_xstreme/sea_out/sea.tsv") %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)
EAR_close_xstreme <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/EAR_close_xstreme/xstreme.tsv") %>% slice_head(n = length(.$ID)-3)
EAR_close_sea_all <- rbind(EAR_close_sea_disc, EAR_close_sea_known) %>% 
  arrange(ID, desc(source == "known")) %>%  
  distinct(ID, .keep_all = TRUE)

```

```{r looking at EAR_close data}
EAR_close_combo <- EAR_close_xstreme %>% 
  dplyr::select(SEED_MOTIF:EVALUE_ACC,SIM_MOTIF) %>% 
  left_join(., EAR_close_sea_all, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF
)) %>% 
  dplyr::select(RANK,CLUSTER,SIM_MOTIF,ALT_ID, ID,CONSENSUS.x,motif_name,EVALUE.y,QVALUE,TP:ENR_RATIO) %>% 
  arrange(.,EVALUE.y) %>% 
  mutate(mrc_type="EAR_close")

EAR_close_combo %>% 
  dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
  kable(., caption = "Enriched motifs 200 bp in EAR open v NR") %>%
  kable_paper("striped", full_width = TRUE) %>%
  kable_styling(full_width = FALSE, font_size = 16) %>%
  scroll_box(height = "500px")

```
```{r EAR_close}
ER_rat <- 1.25
mrc_type <- "EAR_close"
EAR_close_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*1.25), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1.25,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

EAR_close_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>%
  distinct(CLUSTER,.keep_all = TRUE) %>% 
  slice_head(n=5) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*.8), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./.8,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

```


### ESR_open data
```{r ESR_open xstreme output data loading}


ESR_open_sea_disc <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_open_xstreme/sea_disc_out/sea.tsv") %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)
ESR_open_sea_known <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_open_xstreme/sea_out/sea.tsv") %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)
ESR_open_xstreme <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_open_xstreme/xstreme.tsv") %>% slice_head(n = length(.$ID)-3)
ESR_open_sea_all <- rbind(ESR_open_sea_disc, ESR_open_sea_known) %>% 
  arrange(ID, desc(source == "known")) %>%  
  distinct(ID, .keep_all = TRUE)

```

```{r looking at ESR_open data}
ESR_open_combo <- ESR_open_xstreme %>% 
  dplyr::select(SEED_MOTIF:EVALUE_ACC,SIM_MOTIF) %>% 
  left_join(., ESR_open_sea_all, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF
)) %>% 
  dplyr::select(RANK,CLUSTER,SIM_MOTIF,ALT_ID, ID,CONSENSUS.x,motif_name,EVALUE.y,QVALUE,TP:ENR_RATIO) %>% 
  arrange(.,EVALUE.y) %>% 
  mutate(mrc_type="ESR_open")

ESR_open_combo %>% 
  dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
  kable(., caption = "Enriched motifs 200 bp in EAR open v NR") %>%
  kable_paper("striped", full_width = TRUE) %>%
  kable_styling(full_width = FALSE, font_size = 16) %>%
  scroll_box(height = "500px")

```
```{r ESR_open}
ER_rat <- 1.25
mrc_type <- "ESR_open"
ESR_open_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*1.25), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1.25,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

ESR_open_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>%
  distinct(CLUSTER,.keep_all = TRUE) %>% 
  slice_head(n=5) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*10), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./10,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

```

### ESR_close data
```{r ESR_close xstreme output data loading}


ESR_close_sea_disc <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_close_xstreme/sea_disc_out/sea.tsv") %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)
ESR_close_sea_known <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_close_xstreme/sea_out/sea.tsv") %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)
ESR_close_xstreme <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_close_xstreme/xstreme.tsv") %>% slice_head(n = length(.$ID)-3)
ESR_close_sea_all <- rbind(ESR_close_sea_disc, ESR_close_sea_known) %>% 
  arrange(ID, desc(source == "known")) %>%  
  distinct(ID, .keep_all = TRUE)

```

```{r looking at ESR_close data}
ESR_close_combo <- ESR_close_xstreme %>% 
  dplyr::select(SEED_MOTIF:EVALUE_ACC,SIM_MOTIF) %>% 
  left_join(., ESR_close_sea_all, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF
)) %>% 
  dplyr::select(RANK,CLUSTER,SIM_MOTIF,ALT_ID, ID,CONSENSUS.x,motif_name,EVALUE.y,QVALUE,TP:ENR_RATIO) %>% 
  arrange(.,EVALUE.y) %>% 
  mutate(mrc_type="ESR_close")

ESR_close_combo %>% 
  dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
  kable(., caption = "Enriched motifs 200 bp in EAR open v NR") %>%
  kable_paper("striped", full_width = TRUE) %>%
  kable_styling(full_width = FALSE, font_size = 16) %>%
  scroll_box(height = "500px")

```
```{r ESR_close}
ER_rat <- 1.25
mrc_type <- "ESR_close"
ESR_close_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*1.25), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1.25,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

ESR_close_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>%
  distinct(CLUSTER,.keep_all = TRUE) %>% 
  slice_head(n=5) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*1.75), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1.75,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

```

### ESR_opcl data
```{r ESR_opcl xstreme output data loading}


ESR_opcl_sea_disc <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_opcl_xstreme/sea_disc_out/sea.tsv") %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)
ESR_opcl_sea_known <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_opcl_xstreme/sea_out/sea.tsv") %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)
ESR_opcl_xstreme <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_opcl_xstreme/xstreme.tsv") %>% slice_head(n = length(.$ID)-3)
ESR_opcl_sea_all <- rbind(ESR_opcl_sea_disc, ESR_opcl_sea_known) %>% 
  arrange(ID, desc(source == "known")) %>%  
  distinct(ID, .keep_all = TRUE)

```

```{r looking at ESR_opcl data}
ESR_opcl_combo <- ESR_opcl_xstreme %>% 
  dplyr::select(SEED_MOTIF:EVALUE_ACC,SIM_MOTIF) %>% 
  left_join(., ESR_opcl_sea_all, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF
)) %>% 
  dplyr::select(RANK,CLUSTER,SIM_MOTIF,ALT_ID, ID,CONSENSUS.x,motif_name,EVALUE.y,QVALUE,TP:ENR_RATIO) %>% 
  arrange(.,EVALUE.y) %>% 
  mutate(mrc_type="ESR_opcl")

ESR_opcl_combo %>% 
  dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
  kable(., caption = "Enriched motifs 200 bp in EAR open v NR") %>%
  kable_paper("striped", full_width = TRUE) %>%
  kable_styling(full_width = FALSE, font_size = 16) %>%
  scroll_box(height = "500px")

```
```{r ESR_opcl}
ER_rat <- 1.25
mrc_type <- "ESR_opcl"
ESR_opcl_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*1.25), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1.25,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

ESR_opcl_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>%
  distinct(CLUSTER,.keep_all = TRUE) %>% 
  slice_head(n=5) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*.1), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./.1,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

```



### ESR_clop data
```{r ESR_clop xstreme output data loading}


ESR_clop_sea_disc <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_clop_xstreme/sea_disc_out/sea.tsv") %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)
ESR_clop_sea_known <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_clop_xstreme/sea_out/sea.tsv") %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)
ESR_clop_xstreme <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_clop_xstreme/xstreme.tsv") %>% slice_head(n = length(.$ID)-3)
ESR_clop_sea_all <- rbind(ESR_clop_sea_disc, ESR_clop_sea_known) %>% 
  arrange(ID, desc(source == "known")) %>%  
  distinct(ID, .keep_all = TRUE)

```

```{r looking at ESR_clop data}
ESR_clop_combo <- ESR_clop_xstreme %>% 
  dplyr::select(SEED_MOTIF:EVALUE_ACC,SIM_MOTIF) %>% 
  left_join(., ESR_clop_sea_all, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF
)) %>% 
  dplyr::select(RANK,CLUSTER,SIM_MOTIF,ALT_ID, ID,CONSENSUS.x,motif_name,EVALUE.y,QVALUE,TP:ENR_RATIO) %>% 
  arrange(.,EVALUE.y) %>% 
  mutate(mrc_type="ESR_clop")

ESR_clop_combo %>% 
  dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
  kable(., caption = "Enriched motifs 200 bp in EAR open v NR") %>%
  kable_paper("striped", full_width = TRUE) %>%
  kable_styling(full_width = FALSE, font_size = 16) %>%
  scroll_box(height = "500px")

```
```{r ESR_clop}
ER_rat <- 1.25
mrc_type <- "ESR_clop"
ESR_clop_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*1.25), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1.25,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

ESR_clop_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>%
  distinct(CLUSTER,.keep_all = TRUE) %>% 
  slice_head(n=5) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*1.1), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1.1,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

```


### LR_open data
```{r LR_open xstreme output data loading}


LR_open_sea_disc <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/LR_open_xstreme/sea_disc_out/sea.tsv") %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)
LR_open_sea_known <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/LR_open_xstreme/sea_out/sea.tsv") %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)
LR_open_xstreme <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/LR_open_xstreme/xstreme.tsv") %>% slice_head(n = length(.$ID)-3)
LR_open_sea_all <- rbind(LR_open_sea_disc, LR_open_sea_known) %>% 
  arrange(ID, desc(source == "known")) %>%  
  distinct(ID, .keep_all = TRUE)

```

```{r looking at LR_open data}
LR_open_combo <- LR_open_xstreme %>% 
  dplyr::select(SEED_MOTIF:EVALUE_ACC,SIM_MOTIF) %>% 
  left_join(., LR_open_sea_all, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF
)) %>% 
  dplyr::select(RANK,CLUSTER,SIM_MOTIF,ALT_ID, ID,CONSENSUS.x,motif_name,EVALUE.y,QVALUE,TP:ENR_RATIO) %>% 
  arrange(.,EVALUE.y) %>% 
  mutate(mrc_type="LR_open")

LR_open_combo %>% 
  dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
  kable(., caption = "Enriched motifs 200 bp in EAR open v NR") %>%
  kable_paper("striped", full_width = TRUE) %>%
  kable_styling(full_width = FALSE, font_size = 16) %>%
  scroll_box(height = "500px")

```
```{r LR_open}
ER_rat <- 1.25
mrc_type <- "LR_open"
LR_open_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*1.25), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1.25,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

LR_open_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>%
  distinct(CLUSTER,.keep_all = TRUE) %>% 
  slice_head(n=5) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*6), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./6,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

```


### LR_close data
```{r LR_close xstreme output data loading}


LR_close_sea_disc <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/LR_close_xstreme/sea_disc_out/sea.tsv") %>% mutate(source="disc") %>% slice_head(n = length(.$ID)-3)
LR_close_sea_known <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/LR_close_xstreme/sea_out/sea.tsv") %>% mutate(source="known") %>% slice_head(n = length(.$ID)-3)
LR_close_xstreme <- read.delim("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/LR_close_xstreme/xstreme.tsv") %>% slice_head(n = length(.$ID)-3)
LR_close_sea_all <- rbind(LR_close_sea_disc, LR_close_sea_known) %>% 
  arrange(ID, desc(source == "known")) %>%  
  distinct(ID, .keep_all = TRUE)

```

```{r looking at LR_close data}
LR_close_combo <- LR_close_xstreme %>% 
  dplyr::select(SEED_MOTIF:EVALUE_ACC,SIM_MOTIF) %>% 
  left_join(., LR_close_sea_all, by=c("ID"="ID","ALT_ID"="ALT_ID")) %>% 
  mutate(motif_name=case_when(
    str_detect(SIM_MOTIF, "\\(") ~ str_extract(SIM_MOTIF, "(?<=\\().+?(?=\\))"),
    str_detect(SIM_MOTIF, "^MA\\d+\\.\\d+") ~ ALT_ID,
    str_detect(SIM_MOTIF, "^\\d+-") ~ str_replace(SIM_MOTIF, "^\\d+-", ""),
  TRUE ~ SIM_MOTIF
)) %>% 
  dplyr::select(RANK,CLUSTER,SIM_MOTIF,ALT_ID, ID,CONSENSUS.x,motif_name,EVALUE.y,QVALUE,TP:ENR_RATIO) %>% 
  arrange(.,EVALUE.y) %>% 
  mutate(mrc_type="LR_close")

LR_close_combo %>% 
  dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>%
  kable(., caption = "Enriched motifs 200 bp in EAR open v NR") %>%
  kable_paper("striped", full_width = TRUE) %>%
  kable_styling(full_width = FALSE, font_size = 16) %>%
  scroll_box(height = "500px")

```
```{r LR_close}
ER_rat <- 1.25
mrc_type <- "LR_close"
LR_close_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*1.25), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./1.25,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

LR_close_combo %>% 
   dplyr::filter(ENR_RATIO>ER_rat) %>%
  dplyr::select(RANK,CLUSTER,motif_name,SIM_MOTIF,ALT_ID, ID,EVALUE.y,mrc_type,TP.)%>%
  arrange(.,EVALUE.y) %>%
  mutate(log10Evalue= log(EVALUE.y, base = 10)*(-1)) %>%
  distinct(CLUSTER,.keep_all = TRUE) %>% 
  slice_head(n=5) %>% 
  mutate(motif_name=if_else(str_starts(motif_name,"^Z*"),paste(motif_name, RANK, sep="_"), if_else(motif_name=="KLF9",paste(motif_name, RANK,sep="_"),motif_name)))%>%
  ggplot(., aes (y= reorder(motif_name,log10Evalue))) +
  geom_col(aes(x=log10Evalue),fill=mrc_palette[mrc_type]) +
  geom_point(aes(x=`TP.`*2.5), size =4)+
  scale_x_continuous(expand=c (0,.125),sec.axis = sec_axis(transform= ~./2.5,name="Percent of peaks with motif"))+
  theme_classic()+
  ylab("Enriched TF motif")+
  ggtitle(paste( mrc_type,"response peaks(200bp)Enrichment ratio:",ER_rat))

```


```{r motif collection}

meme_motifs_EAR_open <- read_meme("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/EAR_open_xstreme/xstreme.txt")
meme_motifs_ESR_open <- read_meme("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_open_xstreme/xstreme.txt")
meme_motifs_LR_open <- read_meme("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/LR_open_xstreme/xstreme.txt")
meme_motifs_EAR_close <- read_meme("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/EAR_close_xstreme/xstreme.txt")
meme_motifs_ESR_close <- read_meme("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_close_xstreme/xstreme.txt")
meme_motifs_LR_close <- read_meme("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/LR_close_xstreme/xstreme.txt")
meme_motifs_ESR_opcl <- read_meme("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_opcl_xstreme/xstreme.txt")
meme_motifs_ESR_clop <- read_meme("C:/Users/renee/ATAC_folder/ATAC_meme_data/new_analysis/ESR_clop_xstreme/xstreme.txt")

```


```{r eval=FALSE, fig.height=10, include=FALSE}
group_of_memes <- list(EAR_open=meme_motifs_EAR_open,
                    ESR_open=meme_motifs_ESR_open,
                    LR_open=meme_motifs_LR_open,
                    EAR_close=meme_motifs_EAR_close,
                    ESR_close=meme_motifs_ESR_close,
                    LR_close=meme_motifs_LR_close,
                    ESR_opcl=meme_motifs_ESR_opcl,
                    ESR_clop=meme_motifs_ESR_clop)
name_plot <- c("meme_motifs_EAR_open",
                  "meme_motifs_ESR_open",
                    "meme_motifs_LR_open",
                "meme_motifs_EAR_close",
                    "meme_motifs_ESR_close",
                    "meme_motifs_LR_close",
                    "meme_motifs_ESR_opcl",
                    "meme_motifs_ESR_clop")
counter <- 0
for (meme_frame in group_of_memes ){
   counter <- counter +1 
motif_info <- lapply(meme_frame, function(motif) {
  data.frame(
    motif_name = ifelse(is.null(motif@name), NA, motif@name),
    alt_name = ifelse(is.null(motif@altname), NA, motif@altname)  # Handle missing altname
    # Store the position weight matrix (PWM) in a list
    
  )
})
# Combine the individual motif data frames into one long data frame
motif_df <- bind_rows(motif_info)

plots <- lapply(1:nrow(motif_df), function(i) {
  pwm <-meme_frame[[i]]@motif # Extract PWM for each motif
  name <- motif_df$motif_name[i]
  alt_name <- motif_df$alt_name[i]
  
  # Check if the PWM is valid and can be plotted
  if (!is.null(pwm) && is.matrix(pwm)) {
    ggseqlogo::ggseqlogo(pwm,  method="bits") +
      ggtitle(paste("Motif:", name, "\n| Altname:", alt_name)) +
      theme_minimal()
  } else {
    message("Invalid PWM for motif:", name)
    NULL
  }
})
savefile <- paste0("data/Final_four_data/re_analysis",name_plot[counter],".pdf")
plots_per_page <- 16 
multi_page_grobs <- marrangeGrob(plots, nrow = 4, ncol = 4) 
ggsave(savefile, multi_page_grobs)
grid.draw(multi_page_grobs)
}


```
