---
title: "Raodah's data"
author: "ERM"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

```{css, echo=FALSE}
pre {
  max-height: 400px;
  overflow-y: auto;
}

pre[class] {
  max-height: 200px;
}
```

```{r  package loading}
library(tidyverse)
library(kableExtra)
library(broom)
library(RColorBrewer)
# library(ChIPseeker)
# library("TxDb.Hsapiens.UCSC.hg38.knownGene")
# library("org.Hs.eg.db")
# library(rtracklayer)
library(edgeR)
# library(ggfortify)
library(limma)
library(readr)
library(BiocGenerics)
library(gridExtra)
library(VennDiagram)
library(scales)
library(Cormotif)
library(BiocParallel)
library(ggpubr)
library(devtools)
library(eulerr)
# library(genomation)
library(ggsignif)
# library(plyranges)
library(ggrepel)
```


```{r functions}
drug_pal <- c("#8B006D","#DF707E","#F1B72B", "#3386DD","#707031","#41B333")
pca_plot <-
  function(df,
           col_var = NULL,
           shape_var = NULL,
           title = "") {
    ggplot(df) + geom_point(aes_string(
      x = "PC1",
      y = "PC2",
      color = col_var,
      shape = shape_var
    ),
    size = 5) +
      labs(title = title, x = "PC 1", y = "PC 2") +
      scale_color_manual(values = c(
        "#8B006D",
        "#DF707E",
        "#F1B72B",
        "#3386DD",
        "#707031",
        "#41B333"
      ))
  }
pca_var_plot <- function(pca) {
  # x: class == prcomp
  pca.var <- pca$sdev ^ 2
  pca.prop <- pca.var / sum(pca.var)
  var.plot <-
    qplot(PC, prop, data = data.frame(PC = 1:length(pca.prop),
                                      prop = pca.prop)) +
    labs(title = 'Variance contributed by each PC',
         x = 'PC', y = 'Proportion of variance')
  plot(var.plot)
}

calc_pca <- function(x) {
  # Performs principal components analysis with prcomp
  # x: a sample-by-gene numeric matrix
  prcomp(x, scale. = TRUE, retx = TRUE)
}

get_regr_pval <- function(mod) {
  # Returns the p-value for the Fstatistic of a linear model
  # mod: class lm
  stopifnot(class(mod) == "lm")
  fstat <- summary(mod)$fstatistic
  pval <- 1 - pf(fstat[1], fstat[2], fstat[3])
  return(pval)
}

plot_versus_pc <- function(df, pc_num, fac) {
  # df: data.frame
  # pc_num: numeric, specific PC for plotting
  # fac: column name of df for plotting against PC
  pc_char <- paste0("PC", pc_num)
  # Calculate F-statistic p-value for linear model
  pval <- get_regr_pval(lm(df[, pc_char] ~ df[, fac]))
  if (is.numeric(df[, f])) {
    ggplot(df, aes_string(x = f, y = pc_char)) + geom_point() +
      geom_smooth(method = "lm") + labs(title = sprintf("p-val: %.2f", pval))
  } else {
    ggplot(df, aes_string(x = f, y = pc_char)) + geom_boxplot() +
      labs(title = sprintf("p-val: %.2f", pval))
  }
}
```

```{r fixing the labels renee style}
# saveRDS(cardiotox_highConf_3location, "data/Final_four_data/Raodah_location_counts.RDS")
# saveRDS(H3K27ac_countstable,"data/Final_four_data/Raodah_counts_fixed.RDS" )
H3K27ac_countstable<- readRDS("data/Final_four_data/Raodah_counts.RDS")
cardiotox_highConf_3location <-  readRDS("data/Final_four_data/Raodah_location_counts.RDS")


 names(H3K27ac_countstable) = gsub(pattern = "*87-1 *", replacement = "2_", x = names(H3K27ac_countstable))
 names(H3K27ac_countstable) = gsub(pattern = "*77-1 *", replacement = "3_", x = names(H3K27ac_countstable))
 names(H3K27ac_countstable) = gsub(pattern = "*79-1 *", replacement = "4_", x = names(H3K27ac_countstable))
 names(H3K27ac_countstable) = gsub(pattern = "*78-1 *", replacement = "5_", x = names(H3K27ac_countstable))
 names(H3K27ac_countstable) = gsub(pattern = "*71-1 *", replacement = "6_", x = names(H3K27ac_countstable))
 names(H3K27ac_countstable) = gsub(pattern = "3$", replacement = "_3", x = names(H3K27ac_countstable))
 names(H3K27ac_countstable) = gsub(pattern = "24$", replacement = "_24", x = names(H3K27ac_countstable))


```

```{r examine inital data}

PCA_H3_mat <- H3K27ac_countstable%>% 
  as.matrix()

annotation_H3_mat <-  data.frame(timeset=colnames(PCA_H3_mat)) %>% 
  mutate(sample = timeset) %>% 
  separate(timeset, into = c("indv","trt","time"), sep= "_") %>% 
  mutate(time = factor(time, levels = c("3", "24"), labels= c("3 hours","24 hours"))) %>% 
  mutate(trt = factor(trt, levels = c("DOX","EPI", "DNR", "MTX", "TRZ", "VEH"))) 

PCA_H3_info <- (prcomp(t(PCA_H3_mat), scale. = TRUE)) 
PCA_H3_info_anno <- PCA_H3_info$x %>% cbind(.,annotation_H3_mat)
# autoplot(PCA_info)
summary(PCA_H3_info)
# %>% as.tibble() %>% 
#   kable(., caption = "Summary of PCA variables") %>% 
#   kable_paper("striped", full_width = TRUE) %>%
#   kable_styling(full_width = FALSE, font_size = 16) %>%
#   scroll_box(height = "500px")
# cpm(PCAmat, log=TRUE)
pca_plot(PCA_H3_info_anno, col_var='trt', shape_var = 'time')+ggtitle("PCA of raw counts by time and treatment")
        
pca_plot(PCA_H3_info_anno, col_var='trt', shape_var = 'indv')+ggtitle("PCA of raw counts by treatment and individual")


```

```{r filter and do again}
PCA_H3_mat_t <- H3K27ac_countstable %>% 
  dplyr::select('2_DNR_3':'3_VEH_24','6_DNR_3':'6_VEH_24')

anno_H3_mat <-  data.frame(timeset=colnames(PCA_H3_mat_t)) %>%
  mutate(sample = timeset) %>% 
  separate(timeset, into = c("indv","trt","time"), sep= "_") %>% 
  mutate(time = factor(time, levels = c("3", "24"), labels= c("3 hours","24 hours"))) %>% 
  mutate(trt = factor(trt, levels = c("DOX","EPI", "DNR", "MTX", "TRZ", "VEH")))
  
lcpm_h3 <- cpm(PCA_H3_mat_t, log=TRUE)  ### for determining the basic cutoffs
dim(lcpm_h3)

row_means <- rowMeans(lcpm_h3)
lcpm_h3_filtered <- PCA_H3_mat_t[row_means >0,]
dim(lcpm_h3_filtered)

filt_H3_matrix_lcpm <- cpm(lcpm_h3_filtered, log=TRUE)

PCA_H3_info_filter <- (prcomp(t(filt_H3_matrix_lcpm), scale. = TRUE))
summary(PCA_H3_info_filter)

pca_var_plot(PCA_H3_info_filter)

pca_H3 <- calc_pca(t(filt_H3_matrix_lcpm))
pca_H3_anno <- data.frame(anno_H3_mat, pca_H3$x)


pca_H3_anno %>%
  ggplot(.,aes(x = PC1, y = PC2, col=trt, shape=time, group=indv))+
  geom_point(size= 5)+
  scale_color_manual(values=drug_pal)+
   ggrepel::geom_text_repel(aes(label = indv))+
   ggtitle(expression("PCA of log"[2]*"(cpm) Raodah data, same four individuals"))+
  theme_bw()+
  guides(col="none", size =4)+
  labs(y = "PC 2 ", x ="PC 1 ")+
  theme(plot.title=element_text(size= 14,hjust = 0.5),
        axis.title = element_text(size = 12, color = "black"))

pca_H3_anno %>%
  ggplot(.,aes(x = PC3, y = PC4, col=trt, shape=time, group=indv))+
  geom_point(size= 5)+
  scale_color_manual(values=drug_pal)+
   ggrepel::geom_text_repel(aes(label = indv))+
   ggtitle(expression("PCA of log"[2]*"(cpm)  Raodah data, same four individuals"))+
  theme_bw()+
  guides(col="none", size =4)+
  labs(y = "PC 4 ", x ="PC 3 ")+
  theme(plot.title=element_text(size= 14,hjust = 0.5),
        axis.title = element_text(size = 12, color = "black"))

```

### Diff analysis, 3 individual and 5 individuals

3 is 2,3& 6
5 is 1 ,2, 3, 4, 5
```{r diff analysis}
###group for 3 individuals
group <- c( 1,2,3,4,7,8,9,10,1,2,3,5,6,8,9,10,1,2,4,5,6,7,8,9,10)

##group for 5 individuals
# group <- c(1,2,3,4,7,8,9,10,1,2,3,5,6,8,9,10, 1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,4,5,6,7,8,9,10)
# group <- factor(group, levels =c("1","2","3","4","5","6","7","8","9","10"))
# short_names <- paste0(pca_final_four_anno$indv,"_",pca_final_four_anno$trt,"_",pca_final_four_anno$time)

for_group <- data.frame(timeset=colnames(PCA_H3_mat_t)) %>% 
  mutate(sample = timeset) %>% 
  separate(timeset, into = c("indv","trt","time"), sep= "_") %>% 
  unite("test", trt:time,sep="_", remove = FALSE)


dge <- DGEList.data.frame(counts = PCA_H3_mat_t, group = group, genes = row.names(PCA_H3_mat_t))

group_1 <- for_group$test
efit_raodah1 <- readRDS("data/Final_four_data/efit4_raodah1.RDS")
efit_raodah_shared <- readRDS("data/Final_four_data/efit4_raodah_shared.RDS")
dge$group$indv <- for_group$indv
dge$group$time <- for_group$time
dge$group$trt <- for_group$trt
# 
indv <- for_group$indv
# efit4 <- readRDS("data/Final_four_data/efit4_filt_bl.RDS")
# mm <- model.matrix(~0 +group_1)
# colnames(mm) <-  c("DNR_24", "DNR_3", "DOX_24","DOX_3","EPI_24", "EPI_3","MTX_24", "MTX_3","VEH_24", "VEH_3")
# 
# y <- voom(dge$counts, mm,plot =TRUE)
# 
# corfit <- duplicateCorrelation(y, mm, block = indv)
# 
# v <- voom(dge$counts, mm, block = indv, correlation = corfit$consensus)
# 
# fit <- lmFit(v, mm, block = indv, correlation = corfit$consensus)
# # colnames(mm) <- c("DNR_24","DNR_3","DOX_24","DOX_3","EPI_24","EPI_3","MTX_24","MTX_3","TRZ_24","TRZ_3","VEH_24", "VEH_3")
# #
# #
# cm <- makeContrasts(
#   DNR_3.VEH_3 = DNR_3-VEH_3,
#   DOX_3.VEH_3 = DOX_3-VEH_3,
#   EPI_3.VEH_3 = EPI_3-VEH_3,
#   MTX_3.VEH_3 = MTX_3-VEH_3,
#   DNR_24.VEH_24 =DNR_24-VEH_24,
#   DOX_24.VEH_24= DOX_24-VEH_24,
#   EPI_24.VEH_24= EPI_24-VEH_24,
#   MTX_24.VEH_24= MTX_24-VEH_24,
#     levels = mm)
# 
# vfit <- lmFit(y, mm)
# 
# vfit<- contrasts.fit(vfit, contrasts=cm)

# efit_raodah_shared <- eBayes(vfit)

# saveRDS(efit_raodah_shared,"data/Final_four_data/efit4_raodah_shared.RDS")
results = decideTests(efit_raodah_shared)
summary(results)


```
### Cormotif
```{r cormotif3}

for_group3 <- data.frame(timeset=colnames(PCA_H3_mat_t)) %>% 
  mutate(sample = timeset) %>% 
  separate(timeset, into = c("indv","trt","time"), sep= "_") %>% 
  unite("test", trt:time,sep="_", remove = FALSE)
### for 3 individuals {2,3,6}
group_3 <- c( 1,2,3,4,7,8,9,10,1,2,3,5,6,8,9,10,1,2,4,5,6,7,8,9,10)
group_fac_3 <- group_3
groupid_3 <- as.numeric(group_fac_3)
label <- for_group3$sample
compid_3 <- data.frame(c1= c(1,3,5,7,2,4,6,8), c2 = c( 9,9,9,9,10,10,10,10))

y_TMM_cpm_3 <- cpm(PCA_H3_mat_t, log = TRUE)

colnames(y_TMM_cpm_3) <- label

# set.seed(31415)
# cormotif_initial_3 <- cormotiffit(exprs = y_TMM_cpm_3, groupid = groupid_3, compid = compid_3, K=1:8, max.iter = 500, runtype = "logCPM")
cormotif_initial_3 <- readRDS("data/Final_four_data/cormotif_3_raodah_run.RDS")
# saveRDS(cormotif_initial_3,"data/Final_four_data/cormotif_3_raodah_run.RDS")
plotIC(cormotif_initial_3)
plotMotif(cormotif_initial_3)
# head(cormotif_initial_3$bestmotif)


```

